// <auto-generated />
using DESAFIO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DESAFIOO.Migrations
{
    [DbContext(typeof(DesafioContext))]
    partial class DesafioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DESAFIO.Models.estudante", b =>
                {
                    b.Property<int>("matricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("matricula");

                    b.ToTable("estudantes");
                });

            modelBuilder.Entity("DESAFIO.Models.notas", b =>
                {
                    b.Property<int>("codDisciplina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("av1")
                        .HasColumnType("float");

                    b.Property<float>("av2")
                        .HasColumnType("float");

                    b.Property<float>("av3")
                        .HasColumnType("float");

                    b.Property<int>("matricula")
                        .HasColumnType("int");

                    b.Property<float>("media")
                        .HasColumnType("float");

                    b.Property<string>("nomeDisciplina")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("codDisciplina");

                    b.HasIndex("matricula");

                    b.ToTable("notas");
                });

            modelBuilder.Entity("DESAFIO.Models.notas", b =>
                {
                    b.HasOne("DESAFIO.Models.estudante", "estudante")
                        .WithMany("notas")
                        .HasForeignKey("matricula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
